# frozen_string_literal: true

source "https://rubygems.org"

gem "rake"
gem "awesome_print"

# Rubocop
gem "rubocop"
gem "rubocop-shopify", require: false
gem "rubocop-performance", require: false
gem "rubocop-rake", require: false

